<a href="https://colab.research.google.com/github/MalekGhnemat/AI_2025/blob/main/ProblemSolving2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# **List**

In [ ]:
#Q1:-
list1=[1,2,3,4,5,6,7,8,9,10]
for x in list1:
  if x%2==0:
    print(x)

2
4
6
8
10


In [ ]:
#Q2:-
x=[1,9,3,4,5,6]
y=[3,5,6,7,8,9]
for i in x:
  for j in y:
    if i==j:
      print(i)

9
3
5
6


In [ ]:
#Q3:-
x=[1,2,3,4,5,6,7,8,9,10]
y=[]
for i in (x):
    z= len(x)-i
    y.append(x[z])
    z= len(x)-1
print("Reversed List",y)

Reversed List [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [ ]:
#Q4:-
x=[1,3,5,9,11,13]
summ=0
for i in x:
  summ=summ+i
print(summ)


42


In [ ]:
#Q5
x=[9,5,1,5,1,2,3,7]
y=sorted(x)
print(y)
print(y[-2])

[1, 1, 2, 3, 5, 5, 7, 9]
7


# **Tuple**

In [ ]:
#Q1:-
tup1=(1,10,3,8,7)
list1 = list(tup1)
list1.sort()
print("Maximum number = ",list1[-1])
print("Minimum number = ",list1[0])

Maximum number =  10
Minimum number =  1


In [ ]:
#Q2:-
def swapList(myTuple):
    newList=list(myTuple)
    size = len(newList)
    temp = newList[0]
    newList[0] = newList[size - 1]
    newList[size - 1] = temp
    my_tuple=tuple(newList)
    return my_tuple
newList = [12, 35, 9, 56, 24]

print(swapList(newList))


(24, 35, 9, 56, 12)


In [ ]:
#Q3:-
tup1=(1,5,7,4,3,18,9)
a=list(tup1)
a.sort()
tup1=tuple(a)
print(tup1)

(1, 3, 4, 5, 7, 9, 18)


In [ ]:
#Q4:-
tup1=(1,3,5,5,7,8,5,4,6,4)
for i in tup1:
  cnt=0
  for j in tup1:
    if i==j:
      cnt+=1
  print( i ,"==>" ,cnt)

1 ==> 1
3 ==> 1
5 ==> 3
5 ==> 3
7 ==> 1
8 ==> 1
5 ==> 3
4 ==> 2
6 ==> 1
4 ==> 2


# **Dictionary**

In [ ]:
#Q1:-
dict1={"ali":55,"alaa":60,"mohd":45,"raad":41,"hmza":65}
passedStudents=[]
for key,value in dict1.items():
  if value >= 50:
    passedStudents.append(key)

print("Passed Students : ",passedStudents)

Passed Students :  ['ali', 'alaa', 'hmza']


In [ ]:
#Q2:-
dict1={"ali":55,"alaa":60,"mohd":45,"raad":41,"hmza":65}
dict2={"olyan":95,"omar":69,"ahmad":45}

def merge(fdic,sdec):
  fdic.update(sdec)
  return fdic

print(merge(dict1,dict2))

{'ali': 55, 'alaa': 60, 'mohd': 45, 'raad': 41, 'hmza': 65, 'olyan': 95, 'omar': 69, 'ahmad': 45}


In [ ]:
#Q3:-
dict1={"ali":55,"alaa":60,"mohd":45,"raad":91,"hmza":65}
x=[]
for key,value in dict1.items():
    x.append(value)
print(x)
x.sort()
size1 = len(x)-1
print(x[size1])


[55, 60, 45, 91, 65]
91


In [ ]:
#Q4:-
dict1={"ali":55,"alaa":60,"mohd":45,"raad":91,"hmza":65}
x={}
for key,value in dict1.items():
    x.append(value)
print(x)
x.sort()
size1 = len(x)-1
print(x[size1])


[55, 60, 45, 91, 65]
91


In [ ]:
#Q4:-
x={'A':1,'B':2,'C':3,'D':4}
y={}
for key,value in x.items():
  y[value]=key
print("Inverted Dictionary",y)

Inverted Dictionary {1: 'A', 2: 'B', 3: 'C', 4: 'D'}


In [ ]:
#Q5:-
def count_letters(x):
    letter_count={}
    for i in x:
        if i.isalpha():
            i=i.lower()
            if i in letter_count:
                letter_count[i]+=1
            else:
                letter_count[i]=1
    return letter_count

print(count_letters("Hello Malek kk"))



{'h': 1, 'e': 2, 'l': 3, 'o': 1, 'm': 1, 'a': 1, 'k': 3}


# **SET**

In [ ]:
#Q1:-
set1={1,2,4,"ali"}
set2={2,1,5,"omar"}
z=set1.intersection(set2)
print("intersection is ",z)
y=set1.union(set2)
print("union is ",y)


intersection is  {1, 2}
union is  {1, 2, 'omar', 4, 5, 'ali'}


In [ ]:
#Q2:-
list1=[2,5,5,6,7,7,8,9,9,9]
print("this is list : ",list1)

list2=set(list1)
print("after remove any duplicate value",list2)

this is list :  [2, 5, 5, 6, 7, 7, 8, 9, 9, 9]
after remove any duplicate value {2, 5, 6, 7, 8, 9}


In [ ]:
#Q3
set1={1,2,4,"ali"}
set2={2,1,5,"omar"}

def disjoint(x,y):
  w=x.intersection(y)
  if len(w)==0:
    print("no common elements")
  else:
    print("we have common elements")

disjoint(set1,set2)

we have common elements


In [ ]:
#Q4:-
x={1,2,4,"ali"}
y={2,1,5,"omar"}
x.symmetric_difference_update(y)
print(x)

{'ali', 4, 5, 'omar'}


# **IF CONDITION**

In [ ]:
#Q1:-
x=0
if x>0:
  print("this number is positive")
elif x<0:
    print("this number is negative")
else:
  print("this number is zero")

this number is zero


In [ ]:
#Q2:-
x=input("insert year")
x=int(x)
def leapyear(x):
  if x%4==0 :
    print("this is leap year")
  else:
    print("this is not leap year")
leapyear(x)

insert year 2000


this is leap year


In [ ]:
#program to check if a char is vowel or constant
sttr="hmza_MalEk"
vowel="aeiouAEIOU"
for i in sttr:
  if i in vowel:
    print("this char ",i,"is vowel")
  else:
    print("this char ",i,"is constant")

this char  h is constant
this char  m is constant
this char  z is constant
this char  a is vowel
this char  _ is constant
this char  M is constant
this char  a is vowel
this char  l is constant
this char  E is vowel
this char  k is constant


# **WHILE loop**

In [ ]:
#Q1:-
i=1
while i <100:
  if i % 17==0:
    break
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
#Q2:-
sum = 0
while True:
    number = int(input("Enter a number (enter -1 to stop): "))
    if number == -1:
        break
    sum += number
print("The sum of the numbers is:", sum)


Enter a number (enter -1 to stop):  5
Enter a number (enter -1 to stop):  1
Enter a number (enter -1 to stop):  -1


The sum of the numbers is: 6


In [ ]:
i=1
while i <=50:
  if i % 2 !=0:
    print("this number is odd :",i)
  i+=1

this number is odd : 1
this number is odd : 3
this number is odd : 5
this number is odd : 7
this number is odd : 9
this number is odd : 11
this number is odd : 13
this number is odd : 15
this number is odd : 17
this number is odd : 19
this number is odd : 21
this number is odd : 23
this number is odd : 25
this number is odd : 27
this number is odd : 29
this number is odd : 31
this number is odd : 33
this number is odd : 35
this number is odd : 37
this number is odd : 39
this number is odd : 41
this number is odd : 43
this number is odd : 45
this number is odd : 47
this number is odd : 49


# **FOR loop**

In [ ]:
#Q1:-
x=int(input("insert number"))
for i in range(10):
  mul=x*i
  print(x," * " ,i, "is : " ,mul)

insert number5
5  *  0 is :  0
5  *  1 is :  5
5  *  2 is :  10
5  *  3 is :  15
5  *  4 is :  20
5  *  5 is :  25
5  *  6 is :  30
5  *  7 is :  35
5  *  8 is :  40
5  *  9 is :  45


In [ ]:
#Q2:-
str1="hmza_MALEK"
vowel="aeiouAEIOU"
cnt=0
for i in str1:
  if i in vowel:
    cnt+=1
print("the number of vowel char in given string is : ",cnt)

the number of vowel char in given string is :  3


In [ ]:
#Q3:-
list1=[5,8,7,3,6,88,7]
for i in list1:
  if i> 5:
    print(i)

8
7
6
88
7


# **Function**

In [ ]:
#Q1:-??????????????



Factorial is: 362880


In [ ]:
#palindrome ????

Enter a string:  نن


The string is a palindrome


In [ ]:
#Q3:-
from math import sqrt
list1 = [1, 2, 3, 4, 5, 6]
print(list1)
def seq(list1):
  list2=[]
  for i in list1:
    new=(i**2)
    list2.append(new)
  print(list2)
seq(list1)

[1, 2, 3, 4, 5, 6]
[1, 4, 9, 16, 25, 36]


# **recursion**

In [ ]:
#Q1:- ??
def fibon(n):

  if n <= 1:
    return n
  else:
    return fibon(n-1) + fibon(n-2)

print(fibon(7))


13


In [ ]:
#Q2:-
def poe(x,n):
  if n==0:
    return 1
  else:
    return x*(poe(x,n-1))
print(poe(3,2))

9


In [ ]:
#Q3:-
list1=[1,2,4,4,5]
def summ(list1):
  if len(list1)==0:
    return 0
  else:
    return list1[0]+summ(list1[1:])

print(summ(list1))


16


# **Break and continue**

In [ ]:
#Q1
for i in range(1,20):
  if i%3==0:
    continue

  print(i)

1
2
4
5
7
8
10
11
13
14
16
17
19


In [ ]:
#Q2:-
for i in range(1, 51):
    if i % 13 == 0 and i % 7 == 0 :
        break
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [ ]:
#Q3:-
list1=[1,5,6,8,7]
for i in list1:
  if i%2==0:
    break
  print(i)

1
5


# **lambda**

In [ ]:
#sort list of tup based on second element
list1=[(2,4),(3,9),(8,4)]
sort_list=sorted(list1,key=lambda l:l[1] )
print(sort_list)

[(2, 4), (8, 4), (3, 9)]


In [ ]:
#write lambda function that return squre of number

seq=lambda x:x**2
print(seq(3))

9


In [ ]:
#filter out even number from list using filter and lambda function
list1=[2,1,4,5,6,7]
even=list(filter(lambda x:x%2==0,list1))
print(list(even))


[2, 4, 6]


# **OOP**

In [ ]:
#Q1:-
class car:
  def __init__(self,brand,model):
    self.brand=brand
    self.model=model
  def car_details(self):
    print("car details : ",self.brand,self.model)

a=car("changan",2025)
a.car_details()

car details :  changan 2025


In [ ]:
#Q2:-
class parent:
  def __init__(self,name,birthday):
    self.name=name
    self.birthday=birthday

  def full_det(self):
    print("details : ",self.name,self.birthday)

class child(parent):
  def __init__(self,x,y):
    super().__init__(x,y)
    self.x=x
    self.y=y
  def nam(self):
    print("only name",self.x)

a=child("ali",1999)
a.nam()
a.full_det()

only name ali
details :  ali 1999


In [ ]:
#Q3:-
#Inheritance
class Person :
    def __init__(self,name,age,gender):
        self.name =name
        self.age =age
        self.gender =gender

    def printall(self):
        print(self.name)
        print(self.age)
        print(self.gender)

class Employee(Person):
    def __init__(self,name,age,gender,salary):
        Person.__init__(self,name,age,gender) # وراثة خصائص كلاس لكلاس آخر
        self.salary =salary # اضافة خصائص للكلاس الوارث

    def printall(self):
        print(self.name)
        print(self.age)
        print(self.gender)
        print(self.salary)# اضافة نسخة معدلة من دالة (method overriides)

#emp1=Employee("malek",25,"male",25000)
#emp1.printall()

class Manager :
    def __init__(self,name,id,location):
        self.name =name
        self.id =id
        self.location =location

    def printall(self):
        print(self.name)
        print(self.id)
        print(self.location)

class Ceo(Employee,Manager) :# وراثة اكثر من(class) (muliple-inheritance)
    def __init__(self,name,id,location,age,gender,salary):
        Manager.__init__(self,  name,id,location) # وراثة خصائص كلاس لكلاس آخر
        Employee.__init__(self,name,age,gender,salary) # NAME

    def printall(self):
        print(self.name)
        print(self.id)
        print(self.location)
        print(self.age)
        print(self.gender)
        print(self.salary)

ceo1=Ceo("Aous",1,"Amman",15,"male",1000)
ceo1.printall()



Aous
1
Amman
15
male
1000


In [ ]:
#Q4:-
class car:
    count = 0
    def __init__(self):
        car.count += 1

    @classmethod
    def get_count(cls):
        return cls.count

c1 = car()
c2 = car()
print(car.get_count())


2


In [ ]:
#Q5:-
from abc import ABC, abstractmethod

class shape(ABC):
  @abstractmethod

  def area():
    pass
class rect(shape):
  def __init__(self,x,y):
    self.x=x
    self.y=y

  def area(self):
    area=self.x*self.y
    return area

class cir(shape):
  def __init__(self,x):
    self.x=x

  def area(self):
    area=3.14*(self.x**2)
    return area

rec=rect(4,5)
print(rec.area())

circ=cir(5)
print(circ.area())





20
78.5


In [ ]:
#Q6:-
class hmza:
  def __init__(self,name,salary):
    self.name=name
    self.__salary=salary
  def get_salary(self):
    return self.__salary

  def set_salary(self,val):
    self.__salary+=val

a=hmza("ali",600)
print(a.get_salary())
a.set_salary(5)
print(a.get_salary())

600
605


# **JSON**

In [ ]:
#Q1:-
data_dic={"name":"ali","age":24,"city":"amman"}
jso_data=json.dumps(data_dic)
print(jso_data)

{"name": "ali", "age": 24, "city": "amman"}


In [ ]:
#Q2:-
import json
json_data='{"name":"ali","age":24,"city":"amman"}'
data_dict=json.loads(json_data)
print(data_dict)

{'name': 'ali', 'age': 24, 'city': 'amman'}


In [ ]:
#Q3:-
data_dic={"name":"ali","age":24,"city":"amman"}
jso_data=json.dumps(data_dic)
print(jso_data)

# **numpy**

In [ ]:
#Q1
import numpy as np
arr1=np.array([[0,0,0],[0,0,0]])
print(arr1)

[[0 0 0]
 [0 0 0]]


In [ ]:
#Q2:-
import numpy as np
randarr=np.random.randint(1,100,10)
print(randarr)

[48 72 36 75 63 23 38 60 65 92]


In [ ]:
#Q3:-
import numpy as np
arr1=np.array([1,2,4,5,7,8,9])
print(arr1.mean())
print(np.median(arr1))
print(arr1.std())

5.142857142857143
5.0
2.799416848895061


In [ ]:
#Q4:-
import numpy as np
arr1=np.array([1,2,4,5,7,8])
print(arr1.shape)
print(arr1.reshape(2,3))

(6,)
[[1 2 4]
 [5 7 8]]


In [ ]:
#Q5:-
import numpy as np
arr1=np.array([1,2,4,5,7,8])
arr2=np.array([1,6,8,1,7,10])
np.add(arr1,arr2)


array([ 2,  8, 12,  6, 14, 18])

In [ ]:
#Q6:-
import numpy as np
arr1=np.array([[2,4,6],[8,10,12]])
arr2=np.array([[7, 8],
              [9, 10],
              [11, 12]])

result = np.dot(arr1, arr2)
print(result)

[[116 128]
 [278 308]]


In [ ]:
#Q7:-
arr1=np.array([[2,4,6],[8,10,12]])
print(np.max(arr1))
print(np.argmax(arr1))
print(np.min(arr1))
print(np.argmin(arr1))

12
5
2
0


In [ ]:
#Q8:-
import numpy as np
arr1=np.array([[2,4,5],
       [5,6,7],
       [3,2,9],[8,4,6]])

print(arr1[:3,:2])

[[2 4]
 [5 6]
 [3 2]]
